### ISSUE TITLE
Update Colour specs for ISO/IEC 23001 update

### ISSUE THREAD

**Issue by dericed** [cellar-wg/matroska-specification#154]
The colour element definitions were written with reference to ISO/IEC 23001-8:2013/DCOR1 but now the 2016 version is available. I suggest we review and see if we can reference to the new version and if that addresses any of the proposed values that we were anticipating.

**Comment by retokromer** [comment]
A corrigenda is currently discussed: `ISO/IEC 23001-8:2016/DAmd 1`.

And, as this will be replaced by `ISO/IEC DIS 23091-1` (Systems), `ISO/IEC DIS 23091-2` (Video) and `ISO/IEC DIS 23091-3` (Audio), I suggest that we keep an eye on these as well.

**Comment by robUx4** [comment]
Fixed by #256 ?

**Comment by dericed** [comment]
https://github.com/Matroska-Org/matroska-specification/blob/3ee18e28791995b97ae6ef753f82a74cfd98654b/ebml_matroska.xml#L422 still references the 2013 version. Can this be updated to 2016? I don't have a copy, but is it still `Table 4` that we are referencing in the update?

**Comment by retokromer** [comment]
As long as I know, this has been revised by ISO/IEC 23091-1:2018.

**Comment by JeromeMartinez** [comment]
AFAIK ISO/IEC 23091-1:2018 repeats values in 23001-8:2016 or ITU-T H.273:2016 i.e. no new assignments so would not worth it to mention it.

**Comment by dericed** [comment]
closed via https://github.com/cellar-wg/matroska-specification/pull/256 and https://github.com/cellar-wg/matroska-specification/pull/274
