### ISSUE TITLE
document rotation use case with ProjectionPoseRoll Element

### ISSUE THREAD

**Issue by hubblec4** [cellar-wg/matroska-specification#269]
How complicated would it be to add new Matroska TagNames?
In my chatperEditor [thread](https://forum.doom9.org/showthread.php?p=1853015#post1853015)
is a user which uses this TagName to rotate the video while playback.

**Comment by dericed** [comment]
I'm unsure if a string tag is the best way to handle rotation. Perhaps we should consider other examples of handling this, such as the transformation matrix in QuickTime

**Comment by mbunkus** [comment]
Speaking from a practical point of view: is QT's transformation matrix used widely, and specifically, for anything other than rotation? I can see 90/180/270 degree rotation being useful due to people misusing their cameras/phones, but other than that transformations don't sound useful to me at all.

I agree that anything affecting the display/playback of content should not be done via tags but something else; if it's simple enough & static over the whole duration, the track headers.

**Comment by dericed** [comment]
Actually, instead of considering a new Rotation Element, I think the existing `ProjectionPoseRoll` already handles this scenario.

Such as:
```xml
<Projection>
  <!-- '0' = 'rectangular' -->
  <ProjectionType>0</ProjectionType>
  <!-- unstored ProjectionPoseYaw and ProjectionPosePitch
       provide defaults of 0 rotation on right and up vectors -->
  <!-- ProjectionPoseRoll is a float in range of -180 to 180
       for rotation around the forward vector -->
  <ProjectionPoseRoll>$ROTATION</ProjectionPoseRoll>
</Projection>
```

If this is sufficient, I can close #271 and add some documentation to cover a basic rotation example.

**Comment by JeromeMartinez** [comment]
Right, not surprising as the need is not new in video world and WebM needed it.
So IMO 271 need is already fulfilled, and we need to be more careful about not having duplicates.

**Comment by dericed** [comment]
I closed #271 without merge and updated the issue title. Does this approach work for you, @hubblec4?

**Comment by hubblec4** [comment]
OK, an element for rotation exists, but:
There is already a software today with which you can set / change this element.
can a user change the value for this element(or delete the element) without remux the Matroska file?

I'm afraid no player today supports this element.

I guess players which supports rotation via Tags will don't remove this feature.

**Comment by JeromeMartinez** [comment]
> I guess players which supports rotation via Tags will don't remove this feature.

Having a standard method does not prevent tools to support pre-standard method, just that pre-standard method is not always what happens in the standard later.

and IIUC this is from WebM so Google, more tools (e.g. Google tools) will use the Google method instead of the pre-standard stuff.

**Comment by erdemguven** [comment]
Hi, I'm working on ExoPlayer. We found out that a partner is using a custom track name format to encode rotation information. We want them to use a standard method and while searching for one we found this thread.

We discussed this solution with the authors of the [Spherical Video V2](https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md). They said that these fields were not intended to be used for a rectangular video and they think it's odd to partially support the spec for just this use case. 

Also it won't support other use cases like scaling, translation, skewing so they recommend using a transformation matrix like MP4 and others use.

**Comment by erdemguven** [comment]
So do you think it is worth reconsidering using #271 or a transformation matrix?

**Comment by dericed** [comment]
I suppose I'm not sure I agree with the authors of the Spherical Video V2 on this. It seems to me that the spherical elements as defined do handle the situation of rotation quite simply. Interested in finding more consensus on which direction to proceed in.

**Comment by erdemguven** [comment]
Adding @acolwell, one of the authors of the Spherical Video V2, in case he wants to add anything.

**Comment by andrewlewis** [comment]
@dericed @acolwell Currently ExoPlayer only supports some HTC-specific signaling for rotation in Matroska: https://github.com/google/ExoPlayer/commit/42c3ff393413966bcd3743421511a1c05b016ef1. We'd like to support something more standardized, so what's the final decision on ProjectionPoseRoll vs. something else (e.g., a new element with a transform matrix like ISOBMFF)?

**Comment by dericed** [comment]
nudging @robUx4 & @mbunkus to gather consensus here.

IIUC the proposals here are:
1. rotation is already supported via the ProjectionPoseRoll element (@dericed +1, @erdemguven -1)
2. rotation should be supported via a metadata tag (@hubblec4)
3. add a new rotation element (I drafted https://github.com/Matroska-Org/matroska-specification/pull/271/commits but prefer option 1)
4. implementing an mp4 style transformation matrix

**Comment by hubblec4** [comment]
For me is option 1 ok.

**Comment by robUx4** [comment]
Same for me `ProjectionPoseRoll` is the rotation on the Z axis (if you consider X,Y for a flat video). As the `Pose` name suggests it's what the user is suppose to see, not how the video was rotated before encoding.

This value is already supported for 360 videos in VLC it would be easy to support it for flat videos as well.

**Comment by robUx4** [comment]
Seems to be solved.

**Comment by AlexFolland** [comment]
What commit solved it?

**Comment by robUx4** [comment]
Ah I thought we agreed on the way it's supposed to be done and that's using existing elements. But yes, more doc might be needed if it's not clear...

**Comment by erdemguven** [comment]
Looks like the majority is in favor of option 1. To allow progress on this issue, I withdraw my objection. I think the issue can be closed.

We'll add support for rotations using ProjectionPoseRoll to ExoPlayer.

**Comment by hubblec4** [comment]
Yes, we should close this issue.
First, the support of rotation is already there, and second my intention was to add an unofficial TagName to the official list.(@dericed has change the issue title and my intention was lost)

@erdemguven 
Nice to read that you will add support for this official way of rotate a video. It is a step forward.
Is there maybe more interest to add more Matroska Features?
I'm looking for developers which have interest in Matroska Menu(native).

**Comment by erdemguven** [comment]
@hubblec4 I'm not aware of any plan for supporting any Matroska specific feature currently.

**Comment by dericed** [comment]
@erdemguven, I'd like to make sure that the language of the specification still addresses your underlying reservation in option 1. Is there any particular warning or recommendation about the use of this option that you'd like expressed within the document?

Also before closing the issue I'd suggest some documentation on this as using ProjectionPoseRoll for rotation isn't completely intuitive at first glace.

**Comment by hubblec4** [comment]
> Also before closing the issue I'd suggest some documentation on this as using ProjectionPoseRoll for rotation isn't completely intuitive at first glace.

Yes you are right @dericed.


> I'm not aware of any plan for supporting any Matroska specific feature currently.

Why not? Rotation is an extra feature and you will implement it.

**Comment by erdemguven** [comment]
@dericed, perhaps it would be useful to add an example on how to use ProjectionPoseRoll with flat videos.

@hubblec4, you can make feature requests at https://github.com/google/ExoPlayer

**Comment by hubblec4** [comment]
OK, I have open an issue for ExoPlayer.....

**Comment by JerryL1987** [comment]
May I know why use ProjectionPoseRoll but ProjectionPoseYaw to rotate video?
For samrtphone case, user will rotate Z-axis to record video. It should be Yaw rotation.
Anyone can answer me?

**Comment by hubblec4** [comment]
The original thread was a question to add an unofficial TagName to the official TagName list.
This questions was answered within this thread: Answer is NO.
For me is this topic finished and we could close this issue.

How to use ProjectionPosRoll element is another question/issue.

**Comment by dericed** [comment]
IMHO, the ProjectionPosRoll element is already usable, but I think some documentation would be helpful to provide the rotation use case as an example.

**Comment by dericed** [comment]
closed via https://github.com/cellar-wg/matroska-specification/pull/326
