### ISSUE TITLE
Move the WebM flag in a separate document

### ISSUE THREAD

**Issue by robUx4** [cellar-wg/matroska-specification#306]
The `webm` attribute we use in the XML Schema is not defined in the EBML Schema so we should not use them.

This is not an extension either since they are the same elements as Matroska.

We do not intend to replace or do the specification for WebM. This [documention exists](https://www.webmproject.org/docs/container/) and actually lists what parts of Matroska exist in WebM.

We should have a machine readable file that can be combined with the Matroska XML Schema to produce the same semantic information we currently have in one file.

**Comment by dericed** [comment]
IIRC there's a place where we say that custom attributes are allowed.

**Comment by dericed** [comment]
Addressed in https://github.com/cellar-wg/ebml-specification/pull/270 and https://github.com/cellar-wg/matroska-specification/pull/325

**Comment by robUx4** [comment]
Closing as I don't think we'll manage a WebM spec ourselves. The EBML Schema part is done properly.
