### ISSUE TITLE
Try to move the chapter in a separate document

### ISSUE THREAD

**Issue by robUx4** [cellar-wg/matroska-specification#356]
If Chapters is not referenced much in the main document

**Comment by dericed** [comment]
Overall I am not convinced that this is helpful but could be compelled.

**Comment by hubblec4** [comment]
I know I said yesterday at the meeting it would be OK. However, there are already links to the chapters.
Matroska Medium / Soft-Linking: These two features use ordered chapters.
Chapters are not necessary to play, but they can be found in almost all videos today. Chapters are already an important part of a video.

So I do not know exactly what would be better.
The Blu-ray specs(it's a draft only) have 1164 pages, so I think 700 pages for Matroska is OK.

**Comment by hubblec4** [comment]
Last meeting, we said the chapters don't move to an extra document...
can we close this issue?
