### ISSUE TITLE
Languages for audio tracks ESP (SPA) and LAT , spanish and latinamerica spanish.

### ISSUE THREAD

**Issue by felisucoibi** [cellar-wg/matroska-specification#364]
In Spanish there are two audio dubs ALWAYS, the latin america dub, and the spanish dub.

In my experience, these 2 languages are completely different in mkv files. These are 2 different worlds of mkv usage 2 worlds don't mix between them.

By now spanish from spain audio tracks and latin american audio tracks are treated different using SPA for spanish, or LAT for latinamerica. In fact for LAT they use the language LATIN that is in MKV specification and there is in the world only 1 or 2 movies that uses LAT for latin. Instead they use LAT for spanish latinamerica.

It would be nice to have the SPA (ESP) for spanish, and LAT or a new thing for spanis latin, so mkvs can handle properly the two audio tracks and can be detected when parsing.

By now as i said, we use SPA for spanish, LAT por latin spanish.

**Comment by hubblec4** [comment]
This is not possible.
Mosu was asked the same question in his MKVToolNix project.
https://gitlab.com/mbunkus/mkvtoolnix/issues/2730

The alternate IETF-language can be used.

**Comment by felisucoibi** [comment]
Thanks for answer, i'm nobody to say what is right, but mkv should offer what people needs not what ietf says, the reality is that latin and spanish are being used for the south American Spanish and Spanish of Europe, at the end will happen that LAT is not going to be used for latin and will be for spanish latin but, i respect your decissions. Bests.

**Comment by hubblec4** [comment]
IETF languages allows you to set what you want, but the old ISO- format languages are limited and a bit obsolete and Matroska can do nothing in this case.

**Comment by felisucoibi** [comment]
In fact IETF has limitations, because you can set languages by country but for example in spain we have catalonian and 2 kind of dubs, CAT and VAL, a CAT-es is useless becaue there are two different dubs for same content in the same country. In spain we have mkv of animation content that we have CAT, GAL EUS, CAT-VL , CAT-CT, ENG-uk, ENG-us, ESP-es ESP-lat , see that for example there is a LATIN dub for spanish that is noty a country, is a dub for all southamerica, and also as i said a CAT that has 2 dubs.

**Comment by JeromeMartinez** [comment]
> but mkv should offer what people needs not what ietf says,

This is a bit harsh...
IETF offers what people needs while handling technical issues e.g. finding a common name accepted bu most people for a specific language in a specific place.
And [Matroska is becoming an IETF standard](https://datatracker.ietf.org/wg/cellar/about/).
We delegate the technical issues in defining language tags to an other IETF group, more specialized than us in languages.
And fixing the issue at IETF level would help to have this issue fixed for all IETF standards in one shot, rather than hacking each standard one per one.

Looking at [IETF language tag spec](https://tools.ietf.org/rfc/bcp/bcp47.txt), "spanish of southamerica" seems handled (it is explicitly listed as an example in Appendix A):
"es-419 (Spanish appropriate for the Latin America and Caribbean region using the UN region code)"

This tag could maybe be added to MKVToolnix if we have also a fallback value (the ISO one) because the IETF language tag is new in Matroska so not handled by all apps (if it is implemented in MKVToolnix, the next work will be to verify all apps that they handle this new Matroska language tag correctly and send bug reports if not).

**Comment by hubblec4** [comment]
I agree with you, Matroska should handle all languages and language-country combinations.
But how to get is working, I don't know.

**Comment by robUx4** [comment]
Looking at [Jerome's answer here](https://gitlab.com/mbunkus/mkvtoolnix/issues/2730#note_282862288), it seems Matroska already has support for this via IETF language tags. It's currently not implemented anywhere AFAIK. But it will come. 

In the meantime it seems `spa-us` would be a good candidate for American Spanish. If you need the opposite you can use `spa-es` for Spanish from Spain.

**Comment by felisucoibi** [comment]
spa-us is very offensive.

Maybe we can keep using LAT of latin, nobody uses it for real latin.

**Comment by retokromer** [comment]
>Maybe we can keep using LAT of latin, nobody uses it for real latin.

Nobody? That’s offensive as well ;-) AV Latin content actually exists.

**Comment by felisucoibi** [comment]
"Nobody? That’s offensive as well ;-) AV Latin content actually exists."
Maybe ancient roman people or the pope can blame us... for Vatican TV? Anyway, to keep using LAT for latin american dubs is not offensive, is just a way to use the actual options.... create a new ESP-US is very offensive part of the protocol, not a choice of users. I don't think is hard to see the difference.

**Comment by JeromeMartinez** [comment]
> Maybe we can keep using LAT of latin

The fact that you (and some others) use LAT, which is intended for Latin language (used e.g. by a Latin professor teaching Latin courses), for Latin Spanish is something I understand as there is no good/better solution in practice for the moment, but it is not what should be in a spec or at long term, as it is an hack. The spec should not endorse the hack.

If I understand well the issue, it is already "fixed" in the spec by the use of Matroska IETF-language + filling `es-ES` for Spanish from Spain and `es-419` for Spanish from Latin America, and the main issue is the support in muxers and players, which is another task (and need to open an issue on the tracker of each muxer and player). We focus on the spec but having more tools using the new specs is on the todo-list.

**Comment by retokromer** [comment]
>Maybe ancient roman people or the pope can blame us... for Vatican TV?

European history is full of Latin. Each documentary in which a part of an original document is read is tagged as Latin by archivists. To be clear this has **nothing** to do with the Vatican nor the Pope, just with using correctly the existing standards while cataloging AV content.

**Comment by felisucoibi** [comment]
First, there are not latin documentaries, in the whole world, maybe 2-3? or zero?. In the other side you are mixing what people will or use with the protocol, people is UISING LAT as latinamerica dub, and there is nothing you can do to avoid it, your opinion about latin documentarie makes no sense at all. In the other side there is the present and future protocol of mkv where can be usefull to have a good spanish-latin way to tag a  movie. If you don't see the differences of waht i'm talking is pitty.

**Comment by JeromeMartinez** [comment]
> and there is nothing you can do to avoid it

True. As we could not forbid anyone do flag as "French" a track in English it they decides to do it. What is your goal by trying to demonstrate that?

> If you don't see the differences of waht i'm talking is pitty.

I guess it is time to stop this discussion, as it is being aggressive with useless "arguments".

***

Here we intend to debate about a specification, trying to find something that would make sense when included in a group of standards, please respect that.
As we see (no argument provided that it would not be the case) that the spec already handles the issue and that the only reaction to an disagreement with arguments is ad hominem attacks, I suggest to close the issue ticket.

**Comment by mbunkus** [comment]
As said above, the specification does already provide a fine-grained way to specify the language in use via the IETF Language tags. And as said above, this discussion has reached the end of its use.
