### ISSUE TITLE
deprecate LZO compression

### ISSUE THREAD

**Issue by robUx4** [cellar-wg/matroska-specification#376]
Matroska Blocks can be compressed with zlib, bz2 and lzo compression.

zlib and bz2 have decompression libraries available under permisssive licenses (BSD like for bz2 and OSI approved, GPL compatible, non copyleft for zlib).

lzo doesn't have such a permissive library. The [official library](https://www.oberhumer.com/opensource/lzo/) is GPLv2, there is also decompression code that doesn't rely on this library [in FFmpeg](https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/lzo.c) which is LGPLv2 which means grabbing the whole libavutil to compile.

This license is not permissive enough to be used in many closed source products where they don't want to touch any GPL-based license. That means a file that is created with LZO in a GPL/LGPL software may not be read universally because of licensing issues. I think we should avoid it and mark LZO as deprecated.

The LZO compression advantage over others is that it is [very fast to compress/decompress](https://catchchallenger.first-world.info/wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO). But the compression ratio is not good. That is good for realtime transmission but bad for long term storage. In the end automatic tools that test each compression (like mkclean) will never pick it anyway.

**Comment by retokromer** [comment]
>I think we should avoid it and mark LZO as deprecated.

I second.

>The LZO compression advantage over others is that it is very fast to compress/decompress. But the compression ratio is not good.

The paradise does not exist… I agree that for preservation purposes the compression rate is more important.

**Comment by robUx4** [comment]
I found 2 other options with better licenses:

- a [C++ version in MIT license](https://github.com/jackoalan/lzokay) with compression
- a [C# version in MIT license](https://github.com/zivillian/lzo.net) without decompression

They are both based on the [Linux Kernel documentation for LZO](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/lzo.txt).

In libmatroska2 I've been using minilzo GPLv2 but I may try to port one of these in C so I can use it (or simply write a C wrapper around the C++ one). That means there would be an alternative that is MIT license, so freely used by anyone.

**Comment by retokromer** [comment]
Good catch!

**Comment by mkver** [comment]
FYI: lzo decoding in FFmpeg's Matroska demuxer was broken for 11 1/2 years (until [this commit](https://github.com/FFmpeg/FFmpeg/commit/2ff687c17f3542b0e95c3b95fe6c844f3e809ed8)) and no one noticed/complained.

**Comment by JeromeMartinez** [comment]
The value is reserved for LZO for a long time (we won't reuse it), IMO the question is more if it is mandatory for a "conforming player" to support all compression formats (if not, there is no reason to mark that as deprecated, isn't there?).
Additionally, there is no replacement (fast compression/decompression) proposal.

**Comment by robUx4** [comment]
It turns out the [C++ library](https://github.com/jackoalan/lzokay) is okay (pun intended). I added a [C wrapper](https://github.com/jackoalan/lzokay/pull/3) around it. I tested the code against compressed random data with minilzo (up to 65kB buffers) and it's fine.

I also [ported it to C](https://github.com/Matroska-Org/foundation-source/tree/coremake-out/8/libmatroska2/lzokay) as the C++ restriction was too high for libmatroska2, which is in C.

So in the end there is freely available code to anyone and there are even some free specs. We can keep the LZO compression which seems suitable for live transfer of raw data (and not much else).

Unless anyone disagrees, I'll close this issue.

**Comment by retokromer** [comment]
Excellent job, thank you very much!
