### ISSUE TITLE
ebml_schema2html.xsl transform creates empty "level" column

### ISSUE THREAD

**Issue by mbunkus** [cellar-wg/matroska-specification#378]
Running the following yields nice HTML, but the "Level" column is completely empty:

```
xsltproc transforms/ebml_schema2html.xsl ebml_matroska.xml
```

Additionally the row's `class` attribute is incomplete, for example:

```
  <tr class="level">
```

**Comment by robUx4** [comment]
This XSL Transform is currently not used. I'm not sure how it's supposed to be used. It is not used to generate the website in jekyll (which is missing the whole list of elements page).

@ablwr can you clarify how it's supposed to be used and what was the intention ?

**Comment by mbunkus** [comment]
It generates something similar to the table usually produced by `data2spec`, which was used for generating the full specs table on www.matroska.org. I think the initial intention was to have a transformation that could ultimately do the job of `data2spec`.

I'm currently writing a small Ruby script that does this job (with a layout very similar to `ebml_schema2html.xsl` instead of exactly what `data2spec` produced). Maybe we can just use that script from now on and remove `ebml_schema2html.xsl` (as I'm probably the only one updating www.matroska.org's specs table from time to time such a script would definitely suffice).

**Comment by ablwr** [comment]
Yeah what @mbunkus says -- for a while, we were trying to exactly replicate the look-and-feel of matroska.org. I'm sure there is a lot of code that can be cleaned up as this has become a document with IETF standard as the goal, rather than something trying to achieve both, and works towards updating/replacing matroska.org can happen seperately.

**Comment by robUx4** [comment]
A while back I started migration the "spectools" to XSLT. It's a lot cleaner than updating the code with the (undocumented) Core-C XML parser. 

The unfinished work can be found here https://github.com/robUx4/matroska-specification/tree/lavf/3 (yes, it includes generating the FFmpeg code). There's also a branch to replace data2lib2 https://github.com/Matroska-Org/foundation-source/tree/xslt/1

I can easily adapt `ebml_schema2html.xsl` to replace the old data2spec.

**Comment by mbunkus** [comment]
Personally I would have like to have such transformations be expressed in a more approachable programming language (Ruby, Perl, Python…). Would make modifying them much easier. Yes, I can read XSLT stylesheets, I've even read books about them, but me (and probably a lot of other people) are much more comfortable with one of the popular scripting languages (probably Python, then).

> I can easily adapt `ebml_schema2html.xsl` to replace the old data2spec.

No need, I think. At the moment I prefer the new layout (albeit with a couple of modifications such as repeating table headers before each level 1 elemetn, right-aligning certain columns, using somewhat more descriptive terms for data types & column names) and will likely continue with my Ruby script.

I find it much more important to fix `data2lib(2)` so that we can actually generate updated libMatroska(2) sources. Though I could probably whip up a Ruby script for that, too.

**Comment by retokromer** [comment]
> probably Python, then

Perl (I’m too old for Python ;-)

**Comment by robUx4** [comment]
I understand nothing about Ruby, Python or Perl but I do understand XSLT (because it was already used here I had to learn). I understand there's a learning curve. But IMO it's worth it when dealing with an XML source. To the point now I want to turn everything to XML ;)

Also it's more convenient to have everything in this repo so when you change one XSLT, you know where the same thing is used elsewhere if at all.

**Comment by mbunkus** [comment]
Heh :) Alright. It's interesting how different groups of developer have vastly differing prior experience. The developers I usually talk to outside of Matroska pretty much all know at least two or three of the usual scripting languages (Python, Perl, Ruby, JavaScript), while they don't know jack about XML, let alone XSLT or XPath. It's almost all JSON and YAML for them. Therefore I assumed, wrongly obviously, that those languages might be a better fit.

But as pretty much all of us have some-to-great knowledge about XSLT (including e.g. Dave & Ashley, if I remember correctly), I'm fine with staying with XSLT.

> Also it's more convenient to have everything in this repo so when you change one XSLT, you know where the same thing is used elsewhere if at all.

I was definitely NOT arguing against having all scripts & tools & transformations in a single repository. Quite the opposite; I would have uploaded my Ruby thingy to this repo later. Instead I'll try to modify the `ebml_schema2html.xsl` to make it do what I'd like it to.

**Comment by robUx4** [comment]
At first I wanted to update the "spectools" I wrote to generate the website and source code in the C code. But the XML parser/writer we wrote 10 years ago is too messy to use so I looked for alternatives. I started learning Python to do that but quickly stopped when I realized XSLT, that we already used anyway could do it. In the end I like it, there's enough resource online that I can always find my way to do what I want.

**Comment by mbunkus** [comment]
Today I spend a couple of hours trying to start an XSLT for creating `KaxSemantic.{cpp,h}` but quickly learned that this is far from trivial: for each master element I next need to output only their direct children, and that's rather complicated to do in XSLT as the source material is a flat list of elements, and the direct children are limited by "all elements after the current with a level == my level + 1, but only up to the first element whose level is lower than my own level" — a condition I don't think we can express in XPath.

There are no loops in XSLT, obviously; `<xsl:for-each>` always iterates over all matched elements (no way to say "stop here"). I've found a recursive way that's reeeeeally slow. And I'm still at the very beginning stages.

Not having the level as an attribute and having to calculate it from the `path` attribute by counting backslashes isn't optimal either as we cannot use that in XPath expressions either.

In the same time I would have been able to whip up at least one, maybe two scripts in different programming languages to implement what I need. Sure, you can get anything done in XSLT 1, but it isn't necessarily going to be easy.

Just some observations, nothing more. I'd really like to get rid of `data2lib(2)` for the same reason we just got rid of `data2spec`, though. I don't care if the end result is a Ruby/Python script or an XSLT. XSLT would fit with everything else we have so far, of course. Not sure I'll be the one creating that, though.

**Comment by robUx4** [comment]
You can try those files
https://github.com/robUx4/matroska-specification/blob/lavf/3/transforms/schema_2_kaxsematic_cpp.xsl
https://github.com/robUx4/matroska-specification/blob/lavf/3/transforms/schema_2_kaxsematic_h.xsl

With 
```
xsltproc transforms/schema_2_kaxsematic_h.xsl ebml_matroska_valid.xml > kaxsemantic.h
xsltproc transforms/schema_2_kaxsematic_cpp.xsl ebml_matroska_valid.xml > kaxsemantic.cpp
```

I think it's not finished (no handling of the MATROSKA_VERSION >= 2 thingy yet) but it's a good starting point.

XSLT is a limited language, especially as `xsltproc` only understands 1.0. But with the limited tools it can do a lot things combined with XPath. It's probably possible to select exactly the children of an elements with XPath, but I haven't used that. One tricky part is the `+` in the path of a few elements.

**Comment by mbunkus** [comment]
Ah, those look interesting, thanks. I'll probably give them a try tomorrow. Maybe I can take them a bit further to completion.

**Comment by robUx4** [comment]
In fact, scratch that. I looked at `ebml_matroska_valid.xml` I had here and it's an old version of `ebml_matroska.xml` with the old pathes so it will need a bit more adaptation for the current one.
