### ISSUE TITLE
Split website stuff into separate repository?

### ISSUE THREAD

**Issue by mbunkus** [cellar-wg/matroska-specification#386]
As I wrote elsewhere, I'm pretty fed up with the CMS currently used for www.matroska.org, Drupal. It's hell to maintain (I've had to re-do the whole installation from scratch three times already), themes are inflexible, simple things such as adding a bit of custom CSS code are incredibly involved & difficult. I want it gone.

Question is, what would I want to have in its place? One option is another CMS (probably Wordpress as I'm already maintaining several of those). On the other hand, we don't really need a full CMS. For our actual workflows having something git-backed would actually be a much better fit, I think. And indeed, some time ago the plan was to migrate the whole website into Jekyll-powered pages. We partially did that. The result's currently located in this very repository.

And that's where I propose we make some changes. I'd very much like to convert the whole of www.matroska.org to Jekyll. However, I'd like to separate the stuff that's only used for the web site from the stuff that's only used for the specification effort — mostly in order to clearly separate two very different types of content with very different goals. Having a different repository solely for the web site or even the wider technical infrastructure would also concentrate discussion about the day-to-day operations somewhere where they don't interfere with work on the specification. Separation of concerns. On the other hand, it would allow changing the spec-related pages in ways that we might not want the corresponding web sites to look. Who knows?

So here's what I'd like to do:

1. Create a new repository under the Matroska-Org github organisation (not CELLAR-WG as, again,  it's not spec-related); let's call it "matroska-website". It could start as a clone of "matroska-specification".
2. Remove everything related solely to the web site from the "matroska-specification" repo (with proper PRs, of course)
3. Verify that current content on www.matroska.org matches the content of "matroska-website" and migrate those parts that aren't up to date
4. Swap the Drupal-based website on www.matroska.org with Jekyll-generated sites
5. If necessary, implement redirect for certain well-known old URLs that don't match the Jekyll-based page structure in the web server (so that external links stay valid)
6. If things work well, implement push hooks in the "matroska-website" repo to trigger automatic updates on www.matroska.org

Yes, we could simply make www.matroska.org redirect to github's pages service, but I'd slightly prefer not having to rely on github for everything. We'd also have more control over things such as redirect for old URLs.

Thoughts?

**Comment by robUx4** [comment]
I got exactly the same reaction yesterday when I discovered what Jekyll does. It could totally replace Matroska.org and the content can be created in Markdown. A lot easier for anyone.

I also agree the website doesn't belong to the cellar repo, nor any other repo we have. So go on with creating a new one.

I wouldn't mind hosting Matroska.org on github. It is reliable enough. But Jekyll creates static web pages so it can easily be run and hosted anywhere. We can always keep a backup/monitor on github.

The spec could be generated in the backend when editing ebml_matroska.xml (rather than do the XSLT in the browser)  although I'm not sure how to handle proper automatic dependency across repos.

**Comment by robUx4** [comment]
Github Actions could help with the automation but I'm not sure about credentials across repos or even different organizations. Maybe triggering an action or "broadcasting" an event is doable.

**Comment by robUx4** [comment]
This seems doable properly and safely (the credentials are not public) https://blog.marcnuri.com/triggering-github-actions-across-different-repositories/

**Comment by robUx4** [comment]
The official documentation for the feature is [here](https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch). Basically a commit of `ebml_matroska.xml` could trigger an action on the matroska website repo (and one in the libmatroska one, and one in the foundation source, etc).

**Comment by mbunkus** [comment]
That's great!

I've started migrating pages & working on the new repository. A couple of notes on which content I won't migrate (or change drastically in the process):

The whole "Guides" section is so outdated and incomplete that I'll simply skip it completely.

The whole "Downloads" section is so outdated that I'd like to change it drastically. Instead of one page per operating system where the same programs appear time and again, I'd like to convert all of the download pages into a single page where we feature the programs we develop ourselves (mkclean, mkvalidator, MKVToolNix) with slightly bigger sections.

Additionally we can curate a list of tools that we link to by topic (player, editor, tool…). However, I'd like to keep the information down to a minimum: only provide a name, a short description of what the program does and a link to the home page. I especially don't want version numbers and release dates as we don't keep those lists updated anyway, and having outdated information up there only makes me sad.

The "Blog" section only contains a single entry at the moment. I don't know if that's the case due to me having to set up Drupal too often & losing articles along the way or if there ever was more than one entry. I'd like to skip that section for the time being.

I'd also like to remove the "Sponsor" page; we currently aren't sponsored, and if a company ever decides to want to sponsor us (which I find unlikely), they can use the information from the "Contact" page.

I'll remove all links to the project page on SourceForge. We don't use SourceForge anymore, haven't for a long time, and the only reason it still exists there is their asinine policy of never deleting a project.

I'll move a couple of menu entries from below "Technical / Info" to the top level. I'd like to have everything under "Technical" only be about the specs (and their peripheral information such as the diagram etc.).

For the time being the sidebar menu will always show all elements (meaning the "Technical" sub-menu will always be open). Maybe I'll JavaScriptify it someday, or someone else will.

Last but definitely not least: before I actually switch the old page for the new one, I'll provide a preview of the new one for feedback. And I'll publish the repository long before that, of course.

**Comment by robUx4** [comment]
Sounds good. About the blog I don't think I put any "news" in there in a long time. There might be a link to old post archives that we may want to keep (or we just rely on the Wayback Machine or we don't care). They could be static pages if that's the case.

From time to time I get emails about people wanting their software in our (totally outdated) page, sometimes genuine good projects. I agree we should only deal with our own. The time has changed since there was a handful of softwares that can handle Matroska.

**Comment by mbunkus** [comment]
I've created the repository [Matroska-Org/infrastructure](https://github.com/Matroska-Org/infrastructure) with what I've accomplished so far. I've also created an issue there for continuing our discussion there. I'll close the issue in this repo so as not to disturb the specs process any more.
