### ISSUE TITLE
Remove 'recurring' flag for Chapters

### ISSUE THREAD

**Issue by robUx4** [cellar-wg/matroska-specification#435]
Suggested by @hubblec4 in the October IETF meeting.

Chapters are not vital for playback, unlike the Segment Info and Tracks. We don't really need an extra copy.
There's not really any backward compatibility involved here as I don't think tools take care of the Recurring possibility or not.

**Comment by hubblec4** [comment]
For ordered editions and linked Segments the chapters are needed to play the content of a file in a "special" way.
If no chapters are present the file is still be playable (from begin to the end).

The word "recurring" confuse me a bit. German translation says "wiederkehrend" what means a kind of repeating.

If an element is necessary (for playback or other things), there is a mandatory attribute flag which can be set.

What is the reason for such attribute? How helps this flag for a developer?

**Comment by robUx4** [comment]
I think this discussion belongs to the EBML repository as that's not a Matroska specific thing. The [EBML RFC says](https://www.rfc-editor.org/rfc/rfc8794.html#name-identically-recurring-eleme)
> Identically Recurring Elements are permitted to be stored multiple times within the same Parent Element in order to increase data resilience and optimize the use of EBML in transmission.

The recurring element is also tied to the use of CRC, to know which copy to use. I don't know if a CRC would be sufficiently resilient on a large `Chapters` element that contains soft linking (chapter codecs) or medium linking (ChapterSegmentUID). But I agree they are essential playback parts in those cases (ordered chapters is more debatable). So I think we should keep the `recurring` flag for `Chapters`. (and so close this issue)

**Comment by hubblec4** [comment]
> So I think we should keep the recurring flag for Chapters.

OK, it's fine.
