### ISSUE TITLE
Create new Elements to define a language using RFC 5646 instead of 3 letters ISO-639-2

### ISSUE THREAD

**Issue by robUx4** [cellar-wg/matroska-specification#44]
See this thread for more info https://www.ietf.org/mail-archive/web/cellar/current/msg00769.html
And also https://www.ietf.org/mail-archive/web/cellar/current/msg00155.html

Impacted elements are `/Tracks/TrackEntry/Language`, `/Chapters/EditionEntry/ChapterAtom/ChapterDisplay/ChapLanguage` and `/Tags/Tag/SimpleTag/TagLanguage`.

**Comment by hubblec4** [comment]
Hmm... 
To support new language codes like "deu" for germany is a nice idea, but we have to add new elements. And all existing players have to upgrade reading the new EBML elements. 

Would it be possible to add the new language codes in the existing EBML elements without issues?

**Comment by mbunkus** [comment]
Not really, no. We've had several long discussion, both on the CELLAR list and on IRC, how to best approach this, and the consensus was to introduce three new elements and to clearly define how  the presence. or absence of those elements are to be interpreted. Extending the existing three language elements with new values introduces serial problems and doesn't solve the issue that existing players must still be updated to support those hypothetical new values.

**Comment by hubblec4** [comment]
OK, good to know.

If I understand correctly, we need 3 new EBML elements and it is not really clear how to define these elements?

1.) 3 new elements independent with her own new Language codes
or
2.) 3 new elements which indicates that the "old" Language EBML element is used for the new codes,
    like a boolean: false->use old codes; true->use new codes

or are  there other possible ways?

**Comment by mbunkus** [comment]
We already have a pull request open for adding support for the required elements. See the changes in #103  for how to handle the new elements.

**Comment by hubblec4** [comment]
IETF elements are added, could we close this issue?

**Comment by dericed** [comment]
I think so. Resolved by https://github.com/cellar-wg/matroska-specification/commit/7554d5281c92ae7cf4833599c1981008b9d477a9
